// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3ee461epa6IYLasfkJrUwlwDjzje24c',
    appId: '1:425613207536:web:2b23cd9b0429657b971f35',
    messagingSenderId: '425613207536',
    projectId: 'fix-n-go-1808a',
    authDomain: 'fix-n-go-1808a.firebaseapp.com',
    storageBucket: 'fix-n-go-1808a.firebasestorage.app',
    measurementId: 'G-89NZ27JCFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_55wOCCQlebcxJ3a38N_HZ-hQEgi6AU0',
    appId: '1:425613207536:android:19c2eae63fc496f7971f35',
    messagingSenderId: '425613207536',
    projectId: 'fix-n-go-1808a',
    storageBucket: 'fix-n-go-1808a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfqPxIfjtd99iqLgRLdchP-7UTXxJwOg',
    appId: '1:425613207536:ios:2c9cf1ed326c47f2971f35',
    messagingSenderId: '425613207536',
    projectId: 'fix-n-go-1808a',
    storageBucket: 'fix-n-go-1808a.firebasestorage.app',
    iosBundleId: 'com.example.fixnGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfqPxIfjtd99iqLgRLdchP-7UTXxJwOg',
    appId: '1:425613207536:ios:2c9cf1ed326c47f2971f35',
    messagingSenderId: '425613207536',
    projectId: 'fix-n-go-1808a',
    storageBucket: 'fix-n-go-1808a.firebasestorage.app',
    iosBundleId: 'com.example.fixnGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb3ee461epa6IYLasfkJrUwlwDjzje24c',
    appId: '1:425613207536:web:fba8c0eb84c8b7a5971f35',
    messagingSenderId: '425613207536',
    projectId: 'fix-n-go-1808a',
    authDomain: 'fix-n-go-1808a.firebaseapp.com',
    storageBucket: 'fix-n-go-1808a.firebasestorage.app',
    measurementId: 'G-FSREZ6SXTB',
  );
}
